<div class="alineashow">
  <? if ($this->o->type !== "popover"): ?>
    <h1><?= $this->o->title ?> - <?= $this->o->chem_num ?></h1>
  <? endif; ?>

  <? if (strlen($this->o->context)): ?>
    <? if ($this->o->type === "popover"): ?>
      <div class="context collapse">
        <?= $this->o->context ?>
      </div>
      <button class="btn btn-xs btn-primary" data-toggle="collapse" data-target=".context">Contexte</button>
    <? else: ?>
      <div class="context">
        <?= $this->o->context ?>
      </div>
      <hr class="context_body"/>
    <? endif; ?>
  <? endif; ?>


  <div class="body">
    <?= $this->o->body ?>
  </div>

  <div class="answers">
    <ul>
      <? $weight = 1; ?>
      <? $index = 0; ?>
      <? foreach($this->o->answers as $answer): ?>
        <?
          $checked = "";
          if ($this->o->solution & $weight) {
            $checked = "checked";
          }
          $weight <<= 1;
        ?>
        <li>
          <div class="ansltr">
            <?= chr(65 + $index) ?>.
          </div>
          <div class="anspcent">
            <? if ($this->o->count > 0): ?>
              <?= round((isset($this->o->aChecked[$index])?($this->o->aChecked[$index]):(0)) * 100 / $this->o->count); ?> %
            <? endif; ?>
          </div>
          <div class="anschk">
            <input type='checkbox' disabled <?= $checked ?>/>
          </div>
          <div class="ansbody">
            <?= $answer ?>
          </div>
        </li>
        <? $index++ ?>
      <? endforeach; ?>
    </ul>
  </div>
</div><!-- /.alineashow -->
