<?php if(!$GLOBALS["_min"]):?><script src="public/extlib/datatables/jquery.dataTables.js"></script><?php endif; ?>
<?php if(!$GLOBALS["_min"]):?><script src="public/extlib/datatables/DT_bootstrap.js"></script><?php endif; ?>
<?php if(!$GLOBALS["_min"]):?><script src="public/js/admin/examens.js"></script><?php endif; ?>
<?php if( $GLOBALS["_min"]):?><script src="public/compiled/layout_admin.js"></script><?php endif; ?>
<div class='examens'>

<?php /* ?>
<?= Gb_String::formatTable($this->jsp->aQaires, "html") ?>
<?php */ ?>

  <h2>Examens disponibles</h2>
  <table class="dteditor"></table>



</div><!-- .examens -->


<? $this->onready.= <<<HEREDOC
window.adminexamens = new AdminExamens();
window.adminexamens.go();
HEREDOC;
?>
