<?php if( $GLOBALS["_min"]):?><script src="public/compiled/layout_admin.js"></script><?php endif; ?>
<div class='examens'>
  <a class="btn btn-primary" href="<?= $this->urlBilan ?>">Bilan de cet examen</a>
  <h2>Édition d'un examen</h2>

    <?= $this->partial("views/_flash.phtml"); ?>

    <div class='GBFORM examen'>
    <?= $this->gbform->render(); ?>
    </div>



</div><!-- .examens -->


<? $this->onready.= <<<HEREDOC

HEREDOC;
?>
