<script type="x/custom" id="tplqContext">
  <div class='context'>
    <div class='title'><h2><%= title %></h2></div>
    <div class='body'><%= body %></div>
  </div>
</script>
<script type="x/custom" id="tplqAlinea">
  <div class='alineabody'><%= body %></div>
  <div class='alineaanswers'></div>
</script>
<script type="x/custom" id="tplqAlineaAnswer">
  <div class='oneanswer'>
    <div class='letter'><label><%= letter %>: <input type='checkbox' <%= checked %> /></label></div>
    <div class='body'><%= body %></div>
  </div>
</script>
<script type="x/custom" id="tplqRecapConfirm">
  <div class='context'>
    <div class='title'><h2>Fin du questionnaire</h2></div>
    <div class='body'>
      <p>
        Vous êtes arrivé à la fin du questionnaire. Vous pouvez encore vérifier et modifier vos réponses.
        Quand vous serez satisfait, appuyez sur le bouton de validation pour envoyer vos réponses.
        Vous aurez alors votre note, et vous pourrez consulter le corrigé.
      </p>
      <p>
        Attention, une fois le questionnaire validé, vous ne pourrez plus modifier vos réponses.
      </p>
      <p class='pull-right'>
        <button class='btn btn-danger actionsubmit'>Valider le questionnaire</button>
      </p>
    </div>
  </div>
</script>
<script type="x/custom" id="tplqResult">
  <div class='context'>
    <div class='title'><h2>Résultats</h2></div>
    <div class='body'>
      <p>
        score: <%= score %>
      </p>
      <h2>TODO !!! le corrigé !</h2>
    </div>
  </div>
</script>

<div class='container passer'>
  <div class="row">
    <div class="span12">
      <header class="text-center well">
        Questionnaire
      </header>
    </div>
  </div>
  <div class="row qrow">
    <div class="span1 qtabctn">
      <ul></ul>
    </div>
    <div class="span11 qbodyctn"></div>
  </div>
  <div class="row">
    <div class="span12">
      <footer class='text-center well'>
        <button class="btn btn-primary actionprev" href="#"><i class="icon-backward icon-white"></i></button>
        <button class="btn btn-primary actionnext" href="#"><i class="icon-forward icon-white"></i></button>
      </footer>
    </div>
  </div>

</div><!-- .container -->


<? $this->onready.= <<<HEREDOC
mestestsPasser = new MestestsPasser();
mestestsPasser.go();
HEREDOC;
?>
