<?php if(!$GLOBALS["_min"]):?><script src="public/extlib/datatables/jquery.dataTables.js"></script><?php endif; ?>
<?php if(!$GLOBALS["_min"]):?><script src="public/extlib/datatables/DT_bootstrap.js"></script><?php endif; ?>
<?php if( $GLOBALS["_min"]):?><script src="public/compiled/layout_admin.js"></script><?php endif; ?>

<div class='container'>
<div class="bilan">
<?= $this->out ?>
</div>
</div><!-- /.container -->

<? $this->onready.= <<<HEREDOC
var adminStats = new AdminStats();
adminStats.go();
HEREDOC;
?>
