<div class="container">
  <!-- Main hero unit for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Bienvenue !</h1>
    <p>
      Ce site vous permet de vous entraîner à passer le QCM de la PACES. Vous pouvez demander à passer autant
      de tests que vous désirez. À la fin de chaque test, vous obtenez immédiatement votre score et vous
      pouvez comparer vos réponses à la solution.
    </p>
    <? if (isset($this->auth['login'])): ?>
      <p><a href="<?= $this->urlMestests ?>" class="btn btn-primary btn-large">Commencer &raquo;</a></p>
    <? else: ?>
      <p>Vous devez vous connecter afin d'accéder à vos tests.</p>
    <? endif; ?>
  </div>
</div>