<div class='stats'>

<h2>Examens actifs</h2>
<h3>Nombre de questionnaires terminés</h3>
<div class="context nobr">
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_active-day.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_active-week.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_active-month.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_active-year.png" />
</div>

<h3>Moyenne</h3>
<div class="context nobr">
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_active-day.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_active-week.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_active-month.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_active-year.png" />
</div>

<h2>Tous les examens</h2>
<h3>Nombre de questionnaires terminés</h3>
<div class="context nobr">
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_all-day.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_all-week.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_all-month.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_exams_all-year.png" />
</div>

<h3>Moyenne</h3>
<div class="context nobr">
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_all-day.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_all-week.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_all-month.png" />
    <img src="http://pollux4.fcomte.iufm.fr/gbo/munin/dsi/leonard2.dsi/pacexpresso_scores_all-year.png" />
</div>

</div><!-- .stats>
