<?php if(0){$content="";} ?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type"        content="text/html; charset=UTF-8" />
    <base href="<?php echo $this->urlPrefix(getUrlExt()); ?>" />
    <meta name="viewport"                  content="width=device-width, initial-scale=1.0" />
    <meta http-equiv='Content-Script-Type' content='text/javascript'>
    <meta http-equiv='Content-Style-Type'  content='text/css'>
    <meta http-equiv='Content-Language'    content='fr'>
    <meta http-equiv="X-UA-Compatible"     content="IE=edge" />
    <link rel="shortcut icon"              href="about:blank" />

    <!--  shims  -->
<?php if (FALSE): ?>
    <?php if(!$GLOBALS["_min"]):?><script type="text/javascript" src="public/extlib/es5-shim/es5-shim.js"></script><?php endif; ?>
    <?php if(!$GLOBALS["_min"]):?><script type="text/javascript" src="public/extlib/es5-shim/es5-sham.js"></script><?php endif; ?>
    <?php if(!$GLOBALS["_min"]):?><script type="text/javascript" src="public/extlib/es6-shim/es6-shim.js"></script><?php endif; ?>
    <!-- Shim to make HTML5 elements usable in older Internet Explorer versions html5shim.googlecode.com/svn/trunk/html5.js -->
    <!--[if lt IE 9]><script src="public/extlib/html5shiv/html5shiv.js"></script><![endif]-->
    <!--[if lt IE 9]><script src="public/extlib/respond/respond.js"></script><![endif]-->
    <!--[if lt IE 8]><script src="public/extlib/JSON-js/json2.js"></script><![endif]-->
<?php endif; ?>

    <!--  jQuery -->
    <?php if(!$GLOBALS["_min"]):?><script type="text/javascript" src="public/extlib/jquery1/jquery.js"></script><?php endif; ?>

    <!--  Bootstrap -->
    <?php if(!$GLOBALS["_min"]):?><link href="public/extlib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" media="screen"><?php endif; ?>
    <?php if(!$GLOBALS["_min"]):?><link href="public/extlib/twitter-bootstrap/css/bootstrap-theme.css" rel="stylesheet" media="screen"><?php endif; ?>
    <?php if(!$GLOBALS["_min"]):?><script src="public/extlib/twitter-bootstrap/js/bootstrap.js"></script><?php endif; ?>

    <!--  Backbone -->
    <?php if(!$GLOBALS["_min"]):?><script src="public/extlib/lodash-compat/lodash.js"></script><?php endif; ?>

    <!--  Our js / css -->
    <?php if(!$GLOBALS["_min"]):?><script src="public/js/mestests/passer.js"></script><?php endif; ?>
    <?php if(!$GLOBALS["_min"]):?><script src="public/js/admin/stats.js"></script><?php endif; ?>
<?php if (FALSE): ?>
    <?php if(!$GLOBALS["_min"]):?><link type="text/css" href="public/css/default.css" rel="stylesheet" /><?php endif; ?>
<?php endif; ?>
    <?php if(!$GLOBALS["_min"]):?><link type="text/css" href="public/css/custom.css" rel="stylesheet" /><?php endif; ?>

    <?php if( $GLOBALS["_min"]):?><script type="text/javascript" src="public/compiled/layout_all.js"></script><?php endif; ?>
    <?php if( $GLOBALS["_min"]):?><link type="text/css" href="public/compiled/layout_all.css" rel="stylesheet" /><?php endif; ?>

    <meta name="robots" content="noindex, nofollow">
    <title>Evaluations Pharma</title>
</head>
<body class="<?php echo $this->layout->bodyclass ?>">

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?= $this->layout->urlHome ?>">Paces-QCM</a>
        </div><!--/.navbar-header -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <? $active = ""; if ($this->layout->current==="home") {$active = "active"; } ?>
            <li class="<?= $active ?>"><a href="<?= $this->layout->urlHome ?>">Accueil</a></li>
            <? if (isset($this->auth['login'])) :?>
              <? $active = ""; if ($this->layout->current==="mestst") {$active = "active"; } ?>
              <li class="<?= $active ?>"><a href="<?= $this->layout->urlQuests?>">Vos tests</a></li>
            <? endif; ?>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            -->
          </ul>

          <div class="navbar-right">
            <? if (isset($this->auth['login'])) :?>
              <span class="navbar-text">
                Connecté en tant que : <?= $this->auth['login'] ?>
              </span>
              <a href="<?= $this->auth['logoutUrl'] ?>" class='btn btn-default navbar-btn'>Déconnexion</a>
            <? else: ?>
              <span class="navbar-text">
                Vous n'êtes pas connecté
              </span>
              <a href="<?= $this->auth['loginUrl'] ?>" class='btn btn-default navbar-btn'>Connexion</a>
            <? endif; ?>
          </div>

        </div><!--/.navbar-collapse -->
      </div><!--/.container -->
    </div><!--/.navbar -->

    <?php echo $this->yield(); ?>

    <?php if ("devel"===$GLOBALS["_ENV"]): ?>
      <footer style="white-space:pre; font-family:monospace;"><?= Gb_Response::get_footer(); ?></footer>
    <?php else: ?>
      <footer class="container">
        <div class="row">
          <div class="pull-left">
            En cas de problème, envoyez un mail à<br />
            <span class='tt'>gilles.bouthenot@univ-fcomte.fr</span>
          </div>
          <div class="pull-right">
            <a href="public/credits.txt">Credits</a>
          </div>
        </div>
      </footer>
    <?php endif; ?>

<script>
window.jsp = <?= json_encode($this->jsp); ?>;
jQuery(document).ready(function() {
<?= $this->onready ?>
});
</script>

</body>
</html>
